
import type { ContentItem } from '@/types/content';

export const bodySystems: ContentItem[] = [
  {
    id: 'cardiovascular',
    slug: 'cardiovascular',
    title: 'Cardiovascular System',
    summary: 'In-depth review of the cardiovascular system, common ICU conditions, and nursing interventions.',
    content: 'The cardiovascular system, comprising the heart, blood vessels, and blood, is central to critical care. Key anatomical features include the four heart chambers (atria and ventricles), valves (tricuspid, mitral, aortic, pulmonic), and major vessels like the aorta and vena cava. Physiologically, the cardiac cycle (systole and diastole) and electrical conduction system (SA node, AV node, Bundle of His, Purkinje fibers) drive circulation.\\nCommon ICU arrhythmias include atrial fibrillation (AFib), ventricular tachycardia (VTach), ventricular fibrillation (VFib), bradycardias, and supraventricular tachycardias (SVT). Nurses must recognize these and initiate appropriate protocols, often involving ACLS algorithms.\\nHemodynamic monitoring is vital. Arterial lines provide continuous blood pressure and allow for frequent blood sampling; key nursing care involves setup, leveling, zeroing, waveform analysis (identifying the dicrotic notch), and troubleshooting (e.g., damping, catheter whip). Central Venous Pressure (CVP) monitoring reflects right atrial pressure and can guide fluid resuscitation, though its interpretation requires clinical context. Pulmonary Artery Catheters (PACs), less common now, offer comprehensive data including Cardiac Output/Index (CO/CI), Pulmonary Artery Wedge Pressure (PAWP), and Systemic Vascular Resistance (SVR).\\nVasopressors (e.g., Norepinephrine, Phenylephrine, Vasopressin) and Inotropes (e.g., Dobutamine, Milrinone, Dopamine) are frequently used. Norepinephrine is a first-line agent for septic shock due to its potent alpha-adrenergic effects increasing SVR. Dobutamine primarily increases contractility via beta-1 agonism, useful in cardiogenic shock. Nurses titrate these medications based on hemodynamic targets (e.g., MAP >65 mmHg, CI >2.2 L/min/m²), monitoring closely for side effects like tachyarrhythmias or extravasation.\\nConditions like Myocardial Infarction (MI) require rapid assessment (ECG changes like ST elevation for STEMI) and intervention (e.g., PCI, thrombolysis). Acute Decompensated Heart Failure (ADHF) management focuses on reducing preload and afterload and improving contractility. Shock, in its various forms (cardiogenic, hypovolemic, septic, neurogenic, anaphylactic), demands prompt identification and targeted resuscitation. Basic ECG interpretation (PQRST complex, ST segment changes, basic rhythms) and ACLS principles (managing cardiac arrest, symptomatic brady/tachyarrhythmias) are core ICU nursing skills.',
    categoryType: 'Body System',
    keywordsForImage: 'heart anatomy',
  },
  {
    id: 'respiratory',
    slug: 'respiratory',
    title: 'Respiratory System',
    summary: 'Comprehensive guide to respiratory care in the ICU, including ventilation and airway management.',
    content: 'The respiratory system facilitates gas exchange. Key anatomy includes upper airways (nose, pharynx, larynx) and lower airways (trachea, bronchi, bronchioles, alveoli). Gas exchange (O2 in, CO2 out) occurs at the alveolar-capillary membrane.\\nArterial Blood Gas (ABG) analysis is crucial for assessing oxygenation, ventilation, and acid-base status. A systematic approach (pH, PaCO2, PaO2, HCO3, Base Excess) helps identify conditions like respiratory/metabolic acidosis/alkalosis and compensation. Normal values: pH 7.35-7.45, PaCO2 35-45 mmHg, PaO2 80-100 mmHg, HCO3 22-26 mEq/L.\\nMechanical Ventilation supports or replaces spontaneous breathing. Common modes include Assist-Control (AC - either Volume Control or Pressure Control), Synchronized Intermittent Mandatory Ventilation (SIMV), and Pressure Support Ventilation (PSV). Key settings are FiO2 (fraction of inspired oxygen), PEEP (positive end-expiratory pressure), respiratory rate (RR), and tidal volume (VT) or inspiratory pressure (PIP). Lung protective strategies (e.g., low VT 4-6 mL/kg ideal body weight for ARDS) are standard. Nurses monitor ventilator parameters, troubleshoot alarms (high pressure, low volume), and assess patient-ventilator synchrony.\\nAcute Respiratory Distress Syndrome (ARDS) is a severe form of lung injury characterized by bilateral opacities and hypoxemia not fully explained by cardiac failure. Management includes lung-protective ventilation, proning, and conservative fluid strategies. Ventilator-Associated Pneumonia (VAP) is a significant risk; VAP prevention bundles (HOB elevation, daily sedation vacations, oral care with chlorhexidine, PUD/DVT prophylaxis) are critical. Pulmonary Embolism (PE) requires prompt diagnosis and anticoagulation. Weaning from mechanical ventilation involves daily spontaneous breathing trials (SBTs) and assessing readiness for extubation.\\nNon-Invasive Ventilation (NIV), like BiPAP and CPAP, can support patients without intubation. Tracheostomy care involves stoma cleaning, suctioning, cuff pressure monitoring, and inner cannula care. Chest tubes are used for pneumothorax, hemothorax, or pleural effusions; nursing care includes monitoring drainage, checking for air leaks, and ensuring system integrity.',
    categoryType: 'Body System',
    keywordsForImage: 'lungs anatomy',
  },
  {
    id: 'neurological',
    slug: 'neurological',
    title: 'Neurological System',
    summary: 'Focus on neurological assessments, monitoring, and care for critically ill neuro patients.',
    content: 'The neurological system includes the brain (cerebrum, cerebellum, brainstem), spinal cord, and peripheral nerves. Understanding basic neuroanatomy, including lobes of the brain and the Circle of Willis, is key. Cerebrospinal fluid (CSF) pathways are also important.\\nIntracranial Pressure (ICP) monitoring is vital for patients with TBI, stroke, or brain tumors. Normal ICP is 5-15 mmHg. Cerebral Perfusion Pressure (CPP = MAP - ICP) target is typically 60-70 mmHg. Signs of increased ICP include headache, vomiting, altered LOC, pupillary changes, and Cushing\'s Triad (hypertension, bradycardia, irregular respirations). Interventions include HOB elevation (30 degrees), maintaining head midline, mannitol or hypertonic saline administration, and controlled hyperventilation (transiently). External Ventricular Drains (EVDs) can monitor ICP and drain CSF.\\nStroke management differs for ischemic (clot) versus hemorrhagic (bleed) types. Rapid assessment (FAST: Face, Arms, Speech, Time) and NIH Stroke Scale are used. Ischemic strokes may be treated with IV thrombolysis (tPA) if within the window (typically <4.5 hours) or mechanical thrombectomy for large vessel occlusions. Hemorrhagic stroke management focuses on BP control, reversing anticoagulation, and potential surgical intervention.\\nTraumatic Brain Injury (TBI) involves primary (initial impact) and secondary (subsequent hypoxia, ischemia, edema) injury. Care focuses on preventing secondary injury by optimizing CPP, oxygenation, and managing ICP.\\nSeizures, especially status epilepticus, require prompt treatment with benzodiazepines followed by anti-epileptic drugs. Seizure precautions (padded side rails, suction available) should be implemented. Spinal Cord Injury care involves immobilization, managing spinal shock (transient loss of reflexes) and neurogenic shock (hypotension, bradycardia due to loss of sympathetic tone), and monitoring for autonomic dysreflexia (medical emergency characterized by severe HTN, bradycardia, HA, triggered by noxious stimuli below injury level).\\nPupillary assessment (size, equality, reactivity - PERRLA) and Glasgow Coma Scale (GCS - eye opening, verbal response, motor response; score 3-15) are fundamental neuro checks. Sedation in neurocritical care (e.g., propofol, dexmedetomidine) aims to control ICP and patient agitation while allowing for neurological assessments via sedation holidays.',
    categoryType: 'Body System',
    keywordsForImage: 'brain anatomy',
  },
];

export const topics: ContentItem[] = [
  {
    id: 'hemodynamics',
    slug: 'hemodynamics',
    title: 'Hemodynamics',
    summary: 'Understanding and managing hemodynamic parameters in critically ill patients.',
    content: 'Hemodynamics refers to the study of blood flow. Core concepts include Cardiac Output (CO = Heart Rate x Stroke Volume), the volume of blood pumped by the heart per minute (normal 4-8 L/min), and Cardiac Index (CI = CO / Body Surface Area), a more individualized measure (normal 2.5-4 L/min/m²).\\nStroke Volume (SV) is determined by preload, afterload, and contractility. Preload is the ventricular stretch at end-diastole, often estimated by CVP or PAWP (though these are pressure surrogates, not volume). Afterload is the resistance the ventricle must overcome to eject blood, estimated by Systemic Vascular Resistance (SVR) or Pulmonary Vascular Resistance (PVR). Contractility is the intrinsic pumping ability of the heart muscle.\\nArterial lines are used for continuous BP monitoring (systolic, diastolic, Mean Arterial Pressure - MAP) and frequent ABG sampling. Nursing care includes proper setup (transducer leveled to phlebostatic axis, zeroed), waveform analysis (presence of dicrotic notch, assessing for damping or resonance), and site care to prevent infection and complications like thrombosis or hematoma.\\nCentral Venous Pressure (CVP) measures right atrial pressure, reflecting right ventricular preload and intravascular volume status, but must be interpreted in clinical context. Pulmonary Artery Catheters (Swan-Ganz) provide more comprehensive data, including PA pressures, PAWP (an estimate of left atrial pressure/left ventricular end-diastolic pressure), CO/CI, SVR, PVR, and mixed venous oxygen saturation (SvO2). Interpretation helps differentiate shock states and guide therapy. Advanced techniques may include non-invasive CO monitoring devices.\\nTitration of vasoactive medications (vasopressors, vasodilators, inotropes) is based on hemodynamic targets (e.g., MAP >65 mmHg, CI >2.2, adequate urine output, lactate clearance). Nurses must understand the specific effects of each drug and monitor for desired outcomes and adverse effects (e.g., arrhythmias, ischemia, extravasation).',
    categoryType: 'Topic',
    keywordsForImage: 'blood pressure',
  },
  {
    id: 'critical-care-pharmacology',
    slug: 'critical-care-pharmacology',
    title: 'Critical Care Pharmacology',
    summary: 'Essential pharmacology for ICU nurses, focusing on common critical care medications.',
    content: 'Vasopressors increase blood pressure by vasoconstriction. Norepinephrine (Levophed) is a potent alpha and beta-1 agonist, first-line for septic shock. Phenylephrine is a pure alpha-agonist. Vasopressin acts on V1 receptors. Epinephrine has strong alpha and beta effects, used in anaphylaxis and cardiac arrest. Key considerations: extravasation risk (central line preferred), arrhythmias, close hemodynamic monitoring.\\nInotropes increase myocardial contractility. Dobutamine (beta-1 agonist) is used in cardiogenic shock and severe heart failure. Milrinone (PDE3 inhibitor) provides inotropy and vasodilation. Considerations: potential for hypotension (especially if hypovolemic), arrhythmias.\\nSedatives manage anxiety and facilitate mechanical ventilation. Propofol (GABA agonist) has rapid onset/offset but can cause hypotension and respiratory depression; monitor for PRIS. Dexmedetomidine (Precedex, alpha-2 agonist) provides sedation with minimal respiratory depression but can cause bradycardia/hypotension. Benzodiazepines (e.g., Midazolam, Lorazepam) are used for anxiolysis and amnesia but carry risks of delirium and accumulation.\\nAnalgesics manage pain. Opioids (Fentanyl, Morphine, Hydromorphone) are potent but cause respiratory depression, hypotension, and constipation. Non-opioids like Ketamine, NSAIDs (with caution), and Acetaminophen are also used. Multimodal analgesia is preferred.\\nNeuromuscular Blocking Agents (NMBAs/Paralytics) facilitate intubation (e.g., Succinylcholine - depolarizing) or sustained paralysis for ARDS or procedures (e.g., Rocuronium, Vecuronium, Cisatracurium - non-depolarizing). CRITICAL: Ensure adequate sedation and analgesia (use TOF monitoring). Risk of prolonged weakness.\\nAntibiotics are chosen based on suspected/confirmed infection, local resistance patterns. Broad-spectrum initially, then de-escalate based on cultures. Monitor for efficacy and side effects (e.g., nephrotoxicity, ototoxicity).\\nAnticoagulants like Heparin (UFH, monitor aPTT/Anti-Xa, risk of HIT, reversal with Protamine) and LMWH (e.g., Enoxaparin, renal dosing) prevent/treat VTE. DOACs are used less frequently for acute ICU treatment initiation.',
    categoryType: 'Topic',
    keywordsForImage: 'medication pills',
  },
  {
    id: 'ventilator-management',
    slug: 'ventilator-management',
    title: 'Principles and practices of mechanical ventilation in the ICU setting.',
    content: 'Mechanical ventilation aims to support oxygenation and ventilation. Key settings include: FiO2 (target SpO2 >90-92%, lowest possible), PEEP (improves oxygenation, prevents atelectasis, typically 5-20 cmH2O), Tidal Volume (VT, lung protective: 4-8 mL/kg Predicted Body Weight), and Respiratory Rate (RR, adjusted for PaCO2/pH goals).\\nCommon Modes: Assist-Control (AC) guarantees a minimum number of breaths at a set VT (Volume Control - VCV) or set inspiratory pressure (Pressure Control - PCV). Synchronized Intermittent Mandatory Ventilation (SIMV) delivers set mandatory breaths, allowing spontaneous breaths between them, often with pressure support. Pressure Support Ventilation (PSV) augments patient-triggered breaths with a set inspiratory pressure, primarily used for weaning. Pressure Regulated Volume Control (PRVC) delivers a set VT using the lowest possible pressure, adjusting breath-by-breath.\\nAlarm Troubleshooting: High Pressure alarms can indicate kinks, secretions, biting, bronchospasm, pneumothorax, or decreased lung compliance. Low Pressure/Volume alarms suggest disconnections, cuff leaks, or circuit leaks. Apnea alarms indicate insufficient patient effort. Always assess the patient first, then the ventilator and circuit.\\nPatient-Ventilator Synchrony is crucial for comfort and effective ventilation. Dyssynchrony (e.g., double triggering, auto-PEEP, ineffective efforts) can increase work of breathing and VILI risk. Adjustments to ventilator settings or sedation may be needed.\\nLung Protective Ventilation (LPV) is standard, especially in ARDS: low VT, appropriate PEEP, maintaining plateau pressure <30 cmH2O. Permissive hypercapnia may be tolerated. ARDSnet protocols provide guidance.\\nWeaning and Liberation: Daily assessment for readiness includes Spontaneous Breathing Trials (SBTs). Criteria for extubation: stable hemodynamics, adequate oxygenation on minimal support (e.g., FiO2 <40%, PEEP <5-8), ability to protect airway (cough, gag, mental status), and resolution of underlying cause for ventilation.',
    categoryType: 'Topic',
    keywordsForImage: 'hospital ventilator',
  },
];

export const policies: ContentItem[] = [
  {
    id: 'stroke-protocols',
    slug: 'stroke-protocols',
    title: 'Stroke Protocols',
    summary: 'Unit-specific guidelines for the management of acute stroke patients.',
    content: 'Recognize stroke symptoms using FAST (Face drooping, Arm weakness, Speech difficulty, Time to call emergency services). Immediately activate the stroke team. A rapid initial assessment includes establishing Last Known Well (LKW) time and performing the NIH Stroke Scale (NIHSS) by a certified provider. A non-contrast head CT is the priority diagnostic to differentiate ischemic from hemorrhagic stroke.\\nFor Ischemic Stroke: If LKW is within 4.5 hours (extendable in some cases for thrombectomy), assess for IV thrombolysis (tPA/alteplase) eligibility. Key inclusion: ischemic stroke causing measurable neurological deficit. Key exclusions: evidence of hemorrhage on CT, active internal bleeding, recent major surgery/trauma, uncontrolled hypertension (SBP >185 or DBP >110 mmHg despite treatment), known bleeding disorder, current anticoagulant use with elevated INR/PTT. tPA dosage is 0.9 mg/kg (max 90mg), with 10% given as bolus over 1 minute, remainder infused over 60 minutes. Strict BP management post-tPA: maintain SBP <180 mmHg and DBP <105 mmHg. Frequent neuro checks (q15min x2h, q30min x6h, then q1h x16h). Monitor for signs of hemorrhagic conversion (e.g., worsening neuro status, severe headache, N/V).\\nMechanical Thrombectomy may be indicated for Large Vessel Occlusion (LVO) up to 24 hours from LKW in selected patients. Requires coordination with interventional radiology/neurology.\\nFor Hemorrhagic Stroke: Management focuses on controlling blood pressure (target SBP often <140-160 mmHg), reversing any anticoagulation, monitoring for and managing increased ICP, and consulting neurosurgery for potential evacuation of hematoma or management of underlying cause (e.g., aneurysm, AVM).\\nGeneral Supportive Care for all stroke patients: Maintain euglycemia. Treat fever aggressively. Implement VTE prophylaxis (mechanical or pharmacological once bleed risk is stable). Perform dysphagia screening before any oral intake to prevent aspiration. Early mobilization and rehabilitation consults as appropriate.',
    categoryType: 'Policy',
    keywordsForImage: 'brain mri',
  },
  {
    id: 'medication-administration',
    slug: 'medication-administration',
    title: 'Medication Administration Guidelines',
    summary: 'Policies related to safe medication administration in the ICU.',
    content: 'Adherence to the "10 Rights" of medication administration is paramount: Right Patient (two identifiers), Right Drug (check against MAR, look-alike/sound-alike precautions), Right Dose (verify calculations, appropriate for patient), Right Route, Right Time, Right Documentation (timely and accurate), Right Reason (indication), Right Response (monitor for effect), Right to Refuse, and Right Education (patient/family).\\nHigh-Alert Medications (e.g., insulin, anticoagulants, narcotics, sedatives, concentrated electrolytes, vasopressors, NMBAs, chemotherapy) require special safeguards. An independent double-check by two licensed nurses is typically required before administration, including verifying patient, drug, dose, route, rate, and pump settings if applicable.\\nIV medication compatibility must be confirmed using institutional resources (pharmacist, compatibility charts) before mixing or administering via Y-site. Label all IV lines at the port closest to the patient and at the source container.\\nUtilize smart infusion pumps with up-to-date drug libraries. Adhere to standardized concentrations for continuous infusions. Always verify pump settings (drug, concentration, rate, dose, volume to be infused) before initiating an infusion and at handovers.\\nDocumentation must be accurate and contemporaneous. Sign off medications on the MAR immediately after administration, not before. Document patient response, any adverse effects, and, for PRN medications, the indication for administration and its effectiveness. For titratable drips, document titration parameters, patient response, and any changes according to unit protocol (e.g., every 15 minutes to hourly depending on drug and stability).\\nReport medication errors and near misses promptly through the institutional reporting system to facilitate learning and system improvements.',
    categoryType: 'Policy',
    keywordsForImage: 'nurse medication',
  },
  {
    id: 'central-line-care',
    slug: 'central-line-care',
    title: 'Central Line Associated Bloodstream Infection (CLABSI) Prevention',
    summary: 'Protocols for central venous catheter insertion, maintenance, and CLABSI prevention.',
    content: 'CLABSI prevention is a critical patient safety goal. Adherence to bundled interventions is key.\\nInsertion Bundle Practices (performed by inserter, monitored by RN): 1. Hand hygiene before procedure. 2. Maximal barrier precautions during insertion (inserter wears cap, mask, sterile gown, sterile gloves; patient covered with large sterile drape). 3. Skin antisepsis with >0.5% chlorhexidine with alcohol; allow to air dry completely before puncture. 4. Optimal catheter site selection (subclavian preferred over IJ or femoral in adults if possible, based on patient factors and lowest infection risk). 5. Ultrasound guidance for internal jugular and femoral vein cannulation is recommended to reduce mechanical complications and access attempts.\\nMaintenance Bundle Practices (performed by nursing staff): 1. Daily review of line necessity with prompt removal of unnecessary lines. Document daily assessment. 2. Hand hygiene before any manipulation of the line or dressing. 3. "Scrub the Hub": Disinfect catheter hubs, needleless connectors, and injection ports with an appropriate antiseptic (e.g., chlorhexidine, 70% alcohol, povidone-iodine) for at least 15 seconds and allow to dry before each access. 4. Dressing Care: Use sterile, transparent, semipermeable dressings (or CHG-impregnated sponge/dressing if unit protocol and no contraindication). Change dressings if damp, loosened, or visibly soiled, or per institutional protocol (typically q7 days for transparent dressings, q2 days for gauze dressings). Assess site daily for signs of infection. 5. Tubing Changes: Change administration sets for continuous infusions no more frequently than every 96 hours but at least every 7 days. Change tubing used for blood, blood products, or fat emulsions (e.g., propofol) within 24 hours of initiating the infusion (propofol q12h or with each vial change). 6. Ensure all lumens are secured and connectors are consistently disinfected.\\nDrawing Blood Cultures: If CLABSI is suspected, draw paired blood cultures: one from a percutaneous peripheral site and one from each lumen of the CVC, ideally drawn simultaneously. Adhere to strict aseptic technique for all draws. Do not routinely draw cultures from CVCs unless CLABSI is suspected or no other access is available.\\nStaff education and competency validation on CLABSI prevention measures are essential. Monitor adherence to practices and CLABSI rates, providing feedback to the team.',
    categoryType: 'Policy',
    keywordsForImage: 'iv line',
  },
];

export const getAllContentItems = (): ContentItem[] => {
  return [...bodySystems, ...topics, ...policies];
};

